In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
plt.style.use('ggplot')

In [2]:
data_path = "/home/tahas44/Desktop/NYC-Taxi/datas/green_tripdata_2015-01.parquet"
df = pd.read_parquet(data_path)
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2015-01-01 00:31:10,2015-01-01 00:50:41,N,1,255,234,1,5.88,20.0,0.5,0.5,4.1,0.0,None,0.3,25.4,1,1.0,None
1,2,2015-01-01 00:01:05,2015-01-01 00:03:30,N,1,75,74,1,0.89,4.5,0.5,0.5,0.0,0.0,None,0.3,5.8,2,1.0,None
2,2,2015-01-01 00:09:01,2015-01-01 00:33:26,N,1,43,186,1,5.71,22.0,0.5,0.5,0.0,0.0,None,0.3,23.3,1,1.0,None
3,2,2015-01-01 00:17:34,2015-01-01 00:27:07,N,1,80,36,1,1.89,8.5,0.5,0.5,0.0,0.0,None,0.3,9.8,2,1.0,None
4,2,2015-01-01 00:32:38,2015-01-01 00:40:32,N,1,37,17,1,1.07,6.5,0.5,0.5,0.0,0.0,None,0.3,7.8,2,1.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1508488,2,2015-01-31 23:50:32,2015-02-01 00:05:43,N,1,75,230,1,3.91,14.5,0.5,0.5,0.0,0.0,None,0.3,15.8,2,1.0,None
1508489,1,2015-01-31 23:20:01,2015-01-31 23:34:29,N,1,80,112,1,2.00,11.0,0.5,0.5,1.0,0.0,None,0.3,13.3,1,1.0,None
1508490,1,2015-01-31 23:52:30,2015-02-01 00:18:53,N,1,112,79,1,4.70,20.5,0.5,0.5,5.0,0.0,None,0.3,26.8,1,1.0,None
1508491,2,2015-01-31 23:47:51,2015-01-31 23:59:03,N,1,74,250,1,5.98,18.0,0.5,0.5,0.0,0.0,None,0.3,19.3,2,1.0,None
1508492,2,2015-01-31 23:29:31,2015-01-31 23:29:37,N,1,146,146,1,0.00,0.0,0.0,0.0,0.0,0.0,None,0.3,0.0,1,1.0,None

In [5]:
df_ = pd.read_parquet("datas/yellow_tripdata_2016-03.parquet")
df_

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2016-03-01 00:53:35,2016-03-01 00:57:11,1,0.00,1,N,226,226,3,4.0,0.5,0.5,0.00,0.0,0.3,5.30,None,None
1,1,2016-03-01 00:15:13,2016-03-01 00:15:26,1,0.00,1,N,145,145,2,2.5,0.5,0.5,0.00,0.0,0.3,3.80,None,None
2,1,2016-03-01 00:15:46,2016-03-01 00:16:00,1,0.00,1,N,145,145,2,2.5,0.5,0.5,0.00,0.0,0.3,3.80,None,None
3,1,2016-03-01 00:16:17,2016-03-01 00:16:23,1,0.00,1,N,145,145,2,2.5,0.5,0.5,0.00,0.0,0.3,3.80,None,None
4,1,2016-03-01 00:16:45,2016-03-01 00:18:14,1,0.00,1,N,145,145,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12203819,2,2016-03-31 23:05:28,2016-03-31 23:22:56,1,3.10,1,N,79,255,1,15.0,0.5,0.5,1.63,0.0,0.3,17.93,None,None
12203820,2,2016-03-31 23:23:39,2016-03-31 23:28:30,1,1.03,1,N,255,37,2,6.0,0.5,0.5,0.00,0.0,0.3,7.30,None,None
12203821,2,2016-03-31 23:44:11,2016-04-01 00:07:05,1,5.77,1,N,148,146,1,21.5,0.5,0.5,4.56,0.0,0.3,27.36,None,None
12203822,2,2016-03-31 23:21:42,2016-03-31 23:38:22,1,2.13,1,N,68,229,1,12.0,0.5,0.5,1.00,0.0,0.3,14.30,None,None
12203823,2,2016-03-31 23:54:02,2016-03-31 23:56:26,1,0.84,1,N,137,107,1,4.5,0.5,0.5,1.16,0.0,0.3,6.96,None,None

In [6]:
if "airport_fee" in df_.columns:
    print("yes")

yes